# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5dd4dcad569cf4674ac6cffd4f32975f52476fd401a9203eece2fbe6837f0039ebaa6e0ad3b9ae01389faa55ed2029be13d18fc3391f31a4b8bcc2c59946b1

test:
  secret_key_base: 4ec3364673be1e8bc39035b45e3a3d133a8b8b1cc1bb9e4d40eca23b031300a6e62f27be03aa2254b3a871d681efc82789a57748d6f84c1a3095b50f47c871dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
